name: co2114_lab03
channels:
  - defaults
dependencies:
  - python=3.11
  - ipython
  - jupyter
  - matplotlib
  - pip
  - pip:
    - pygame
    - "-e git+https://github.com/wilocw/co2114-codebase.git@2024#egg=agent&subdirectory=lab/src/2"