name: co2114_lab05
channels:
  - defaults
dependencies:
  - python=3.11
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pip
  - pip:
    - pygame
    - "git+https://github.com/wilocw/co2114-codebase.git@2024#egg=agent&subdirectory=lab/src/2"
    - "git+https://github.com/wilocw/co2114-codebase.git@2024#egg=search&subdirectory=lab/src/3"
    - "git+https://github.com/wilocw/co2114-codebase.git@2024#egg=optimisation&subdirectory=lab/src/4"
    - "git+https://github.com/wilocw/co2114-codebase.git@2024#egg=constraints&subdirectory=lab/src/5"